name: Publish

on:
  push:
    tags:
      - "**"

permissions:
  contents: read
  packages: write

jobs:
  cargo:
    uses: majksa-actions/workflows/.github/workflows/docker-build-and-publish.yml@v1
    with:
      platforms: '["linux/amd64"]'
